### ISSUE TITLE
roundRect might be better as an extension to CanvasPath mixin

### ISSUE THREAD

**Issue by Kaiido** [fserb/canvas2D#7]
The current proposal makes `CanvasRoundRect` about the same interface as [CanvasRect][1], but I don't see the rationale for this choice.

As a web author I would prefer to have a `roundRect()` extension to the [CanvasPath][2] mixin, allowing to store it in Path2D objects maybe along with other shapes, or use it with methods like `clip`, `isPointIn...`, `scrollToPath` etc. and also allowing to `fill` or `stroke` many such shapes in a single call (with non negligible performance improvements).

I don't really see the point of having it outside of the "current path" and having an other method to clear pixels doesn't seem really useful either (we can already use compositing + `fill()` to clear from any path).

[1]: https://html.spec.whatwg.org/multipage/canvas.html#canvasrect
[2]: https://html.spec.whatwg.org/multipage/canvas.html#canvaspath

**Comment by fserb** [comment]
cc @mysteryDate

**Comment by mysteryDate** [comment]
This seems totally reasonable to me. I'll see if there are objections on whatwg.

**Comment by Kaiido** [comment]
I believe #8 handled it, closing this.
